# Generated by Django 2.2.5 on 2019-10-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='players',
            new_name='player',
        ),
    ]
